name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/
  legacy:
    required: true
    description: "Whether to obtain VERSION and REVSION from legacy files or not"
    default: "false"

runs:
  using: "composite"
  steps:
      - name: Compile
        run: |
          SRC_FOLDER=$(pwd)/src

          if [[ ${{ inputs.legacy }} == "false" ]]; then
            VERSION="v$(grep '"version"' VERSION.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
            REVISION=`grep '"stage"' VERSION.json | sed -E 's/.*"stage": *"([^"]+)".*/\1/'`
          else
            VERSION=$(cat src/VERSION)
            REVISION=$(cat src/REVISION)
          fi

          echo $VERSION
          echo $REVISION

          cd ${{ inputs.path }}
          mkdir -p build && cd build
          cmake -DSRC_FOLDER=${SRC_FOLDER} -DVERSION="$VERSION" -DREVISION="$REVISION" .. && make -j2
        shell: bash
