name: "Vulnerability Scanner Content generation"
description: "Executes the vulnerability scanner tools to generate the content and compress it."

inputs:
  legacy:
    required: true
    description: "Whether to obtain VERSION and REVSION from legacy files or not"
    default: "false"

runs:
  using: "composite"
  steps:
  # Dependencies
  - name: Project dependencies
    uses: ./.github/actions/vulnerability_scanner_deps

  # Router
  - name: Router - Compilation
    uses: ./.github/actions/compile_and_test
    with:
      path: src/shared_modules/router
      test: false
      legacy: ${{ inputs.legacy }}

  # Indexer connector
  - name: Indexer connector - Compilation
    uses: ./.github/actions/compile_and_test
    with:
      path: src/shared_modules/indexer_connector
      test: false
      legacy: ${{ inputs.legacy }}

  # Content manager
  - name: Content manager - Compilation
    uses: ./.github/actions/compile_and_test
    with:
      path: src/shared_modules/content_manager
      test: false
      legacy: ${{ inputs.legacy }}

  # Vulnerability scanner
  - name: Vulnerability scanner - Compilation
    uses: ./.github/actions/compile_and_test
    with:
      path: src/wazuh_modules/vulnerability_scanner
      test: false
      legacy: ${{ inputs.legacy }}
