name: Python lint
on: 
  pull_request:
    paths:
      - '.github/workflows/python-lint.yml'
      - 'api/**'
      - 'apis/**'
      - 'framework/**'
      - 'integrations/**'
      - 'wodles/**'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
