name: Python lint
on: 
  pull_request:
    paths:
      - '.github/workflows/python-lint.yml'
      - 'api/**'
      - 'apis/**'
      - 'framework/**'
      - 'integrations/**'
      - 'wodles/**'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: astral-sh/ruff-action@v2
        with:
          args: ruff check $(git diff --name-only ${{ github.event.before }} )
